### ISSUE TITLE
Problem: Failed to open gpio direction for writing!

### ISSUE THREAD

**Issue by filip-dahlberg** [Infineon/linux-optiga-trust-m#12]
Environment: Embedded Linux 

I'm receiving following error no matter what program I'm invoking from CLI bin. It seems like the CLI programs cannot establish I2C communication to the optiga trust IC due to permission faults. 
![image](https://user-images.githubusercontent.com/37364201/108075763-043f4900-706b-11eb-8343-57bfd56e2214.png)

I know that the I2C connection to the optiga trust m is available from executing trustx_scan. See output of trustx_scan -b /dev/i2c-0:

![image](https://user-images.githubusercontent.com/37364201/108076297-90517080-706b-11eb-9716-baaa94dc90af.png)

Would very much appreciate any help that can point me in right direction.

**Comment by ayushev** [comment]
Hello @MScMechatronics 
just to quickly check, did you change the GPIO settings [here](https://github.com/Infineon/optiga-trust-m/tree/eaf4203e88b5e8da8318e0d27c338e96c4064cd4/pal/linux/target) according to your board?
Did you sucesfully compile the code with no problems on this board?

**Comment by MScMechatronics** [comment]
Thank you very much for your prompt response.

Yes I'm successfully compiled the code by executing the commands in the README:
make workaround_patch
make 
sudo make install

Thanks for your advice on the PAL, I'll check that'll one out. It could also be some kind of driver issue on my side.

However, as the (https://github.com/Infineon/i2c-utils-optiga-trust#trustx_scan)[trustx_scan] program finds the optiga chip through the I2C driver I was thinking that the Infineon/cli-optiga-trust-m bin program were also to work.

**Comment by ayushev** [comment]
The trustx_scan tool is indeed a first tool to understand whether you have a proper communcation in general. It just uses a generic `/dev/i2c-1` device to probe the connection. Whereas the cli uses also the Reset and Power Control Lines (GPIOs) to communication with the chip.
If you would like to skip this part and not use the GPIO (use e.g. software reset), you can just change the configuration ([here](https://github.com/Infineon/optiga-trust-m/blob/eaf4203e88b5e8da8318e0d27c338e96c4064cd4/optiga/include/optiga/optiga_lib_config.h#L119) for m1 or [here](https://github.com/Infineon/optiga-trust-m/blob/trust_m1_m3/optiga/include/optiga/optiga_lib_config_m_v3.h#L114) for m3)

**Comment by MScMechatronics** [comment]
Thanks ayushev , I very much appreciate your help. I now think I have clear understanding of how to proceed.

**Comment by MScMechatronics** [comment]
I now manage to get response from the optiga IC by changing to /dev/i2c-0 [here](https://github.com/Infineon/optiga-trust-m/blob/eaf4203e88b5e8da8318e0d27c338e96c4064cd4/pal/linux/pal_i2c.c#L53). I'm still experiencing the problem with "Problem: Failed to open gpio direction for writing!" which then seem to be a result of trying to write to reset/vdd GPIO, even if I configure it to not use the reset and vdd GPIOs by setting [OPTIGA_COMMS_DEFAULT_RESET_TYPE](https://github.com/Infineon/optiga-trust-m/blob/eaf4203e88b5e8da8318e0d27c338e96c4064cd4/optiga/include/optiga/optiga_lib_config.h#L119) to 1.

**Comment by ayushev** [comment]
To make fast and working setup you might just change [this](https://github.com/Infineon/optiga-trust-m/blob/eaf4203e88b5e8da8318e0d27c338e96c4064cd4/pal/linux/target/rpi3/pal_ifx_i2c_config.c#L73) and [this](https://github.com/Infineon/optiga-trust-m/blob/eaf4203e88b5e8da8318e0d27c338e96c4064cd4/pal/linux/target/rpi3/pal_ifx_i2c_config.c#L82) lines to NULL
as soon as they are defined, the code will try to initialise the gpios. It shouldn't use them, but will try to initialize.
With the address changed, were you able to run the commands?
