### ISSUE TITLE
Bypass Shielded Communication by default

### ISSUE THREAD

**Issue by ayushev** [Infineon/linux-optiga-trust-m#19]
**Is your feature request related to a problem? Please describe.**

It is not obvious and not described anywhere that calling a command without an `-X` option will trigger SEC counter growing up, event data read.

**Describe the solution you'd like**

make the choice reversed, leave the -X for backward compatibility but mark it as deprecated + add a special option to actively enable shielded communication. By default the communication should bypass the shielded connection.

**Additional context**

https://github.com/Infineon/optiga-trust-m/issues/67 shows that `-X` usage isn't obvious

**Comment by RaymWong** [comment]
Add important notes for users to decide whether to disable the Shielded connection based on their application.
https://github.com/Infineon/linux-optiga-trust-m#important-notes
