### ISSUE TITLE
Offset is not zeroed before usage in case of a write command

### ISSUE THREAD

**Issue by ayushev** [Infineon/linux-optiga-trust-m#21]
**Prerequisites**

**Can you reproduce the problem reliably?**
Yes, depending on the compiler the offset value isn't zeroed and initialized with a  random value

**Did you check current release notes for known issues?**
Yes, not mentioned

If this is not the latest release, have you checked newer releases? 

**Description**:

The offset value isn't initialized in case of the write operation, but it is done so for the read and clear operations. Initially reported here - https://github.com/Infineon/linux-optiga-trust-m/discussions/22 

**Expected Result:**

offset should be initialized, in general this is a good practice to have variables be always defined at the beginning of the function.

**Actual Result:**

offset isn't defined and depending on the compiler can contain various values.

**Frequency (1/1, 1/50, 1/100):**

undefined, depends on a compiler

**Build/Commit:**

Please specify the release, like 1.4.1. If there is no release, give us the commit for the code you used.

**Target:**

N/A, reported by a developer

**Host OS and Version:**

N/A, reported by a developer

**Compiler:**

N/A, reported by a developer

Include the version!

**Environment**

Provide the context surrounding this problem. Perhaps an IDE, a debug probe, an RTOS, etc. (and versions)

**Comment by RaymWong** [comment]
Issue is fixed 

https://github.com/Infineon/linux-optiga-trust-m/tree/d03a61fff2693155e6ceb734e002dc7361d9a6e0
