### ISSUE TITLE
Error message when loading trustm_engine in openssl : Undefined symbol: optiga_lib_status 

### ISSUE THREAD

**Issue by janborch** [Infineon/linux-optiga-trust-m#23]
**Description**:

I get an error message `Undefined symbole: optiga_lib_status` when loading the trustm_mengine in openssl

The trustm_* tools work , see below output of trustm_chipinfo

Libtrustm.so is loaded 
```
strings -n5 /etc/ld.so.cache | grep libtrust
libtrustm.so
/lib/arm-linux-gnueabihf/libtrustm.so
```

Looks like the symbol is defined in `libtrustm.so` 

```
nm -gD /lib/arm-linux-gnueabihf/libtrustm.so |grep  optiga_lib_status
000565dc B optiga_lib_status
```
Do I need to load the `libtrustm.so` in openssl? I tried referencing the lib explicitly in the openssl `engine` parameter `MODULE_PATH`  but it did not help.

The only thing I haven't tried is downgrading to openssl 1.1.1d, currently using the latest version 1.1.1n

**Steps to Reproduce:**

```
openssl rand -engine trustm_engine -base64 1024
```

**Expected Result:**
no error

**Actual Result:**
```
069947968:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:../crypto/dso/dso_dlfcn.c:118:filename(/usr/lib/arm-linux-gnueabihf/engines-1.1/trustm_engine.so): /usr/lib/arm-linux-gnueabihf/engines-1.1/trustm_engine.so: undefined symbol: optiga_lib_status
3069947968:error:25070067:DSO support routines:DSO_load:could not load the shared library:../crypto/dso/dso_lib.c:162:
3069947968:error:260B6084:engine routines:dynamic_load:dso not found:../crypto/engine/eng_dyn.c:414:
3069947968:error:2606A074:engine routines:ENGINE_by_id:no such engine:../crypto/engine/eng_list.c:421:id=trustm_engine
3069947968:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:../crypto/dso/dso_dlfcn.c:118:filename(libtrustm_engine.so): libtrustm_engine.so: cannot open shared object file: No such file or directory
3069947968:error:25070067:DSO support routines:DSO_load:could not load the shared library:../crypto/dso/dso_lib.c:162:
3069947968:error:260B6084:engine routines:dynamic_load:dso not found:../crypto/engine/eng_dyn.c:414:
```

**Frequency (1/1, 1/50, 1/100):**
1/1

**Build/Commit:**

Branch development_v3

**Target:**
```
> ./trustm_chipinfo
Read Chip Info [0xE0C2]: Success.
========================================================
CIM Identifier             [bCimIdentifer]: 0xcd
Platform Identifer   [bPlatformIdentifier]: 0x16
Model Identifer         [bModelIdentifier]: 0x33
ID of ROM mask                  [wROMCode]: 0x9301
Chip Type                    [rgbChipType]: 0x00 0x1c 0x00 0x05 0x00 0x00
Batch Number              [rgbBatchNumber]: 0x0a 0x09 0xa4 0x13 0x00 0x0a
X-coordinate              [wChipPositionX]: 0x00b1
Y-coordinate              [wChipPositionY]: 0x005e
Firmware Identifier [dwFirmwareIdentifier]: 0x80101071
Build Number                 [rgbESWBuild]: 24 40

Chip software build:
OPTIGA(TM) Trust M rev.3; Firmware Version: 3.00.2440
========================================================
```

**Host OS and Version:**

Linux raspberrypi 5.15.32-v7l+ #1538 SMP Thu Mar 31 19:39:41 BST 2022 armv7l GNU/Linux

OPenssl : OpenSSL 1.1.1n  15 Mar 2022

**Compiler:**

gcc --version
gcc (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110

**Comment by sgsharath123** [comment]
@janborch We reproduced your issue on our side, please wait until we find the root cause.

**Comment by RaymWong** [comment]
@janborch 
Seems like the gcc version >=9 will exhibit the same behavior that the shared libraries were not linked correctly.
a short term fix would be to downgrade the gcc to version 8 by
sudo apt-get install gcc-8
change the CC = gcc-8 in the makefile 
https://github.com/Infineon/linux-optiga-trust-m/blob/a3bdf70a51dae0b7909388823ed60c0d351ea875/Makefile#L127

**Comment by ying-css** [comment]
@janborch  
It seems gcc 10.2 has issue to link the shared libraries. The second option we found is using gcc-10.1 by following the steps listed as below:
Step1: Follow the steps listed on the link shown here: [Install gcc-10.1](https://solarianprogrammer.com/2017/12/08/raspberry-pi-raspbian-install-gcc-compile-cpp-17-programs/)
Step2: Run `sudo ln -s /usr/include/arm-linux-gnueabihf/openssl /usr/include/openssl`
Step3: Modify the `CC = gcc-10.1` in the makefile
https://github.com/Infineon/linux-optiga-trust-m/blob/a3bdf70a51dae0b7909388823ed60c0d351ea875/Makefile#L127
Step4: Add the `INCDIR += /usr/include/openssl` after Line 65 in the makefile
https://github.com/Infineon/linux-optiga-trust-m/blob/a3bdf70a51dae0b7909388823ed60c0d351ea875/Makefile#L65

**Comment by janborch** [comment]
I confirm - downgrading to gcc-8 works. I can now use the `-engine trustm_engine` option with openssl. Thx!

**Comment by RaymWong** [comment]
> I confirm - downgrading to gcc-8 works. I can now use the `-engine trustm_engine` option with openssl. Thx!

@janborch 
Thanks for your feedback. :)
FYI. Latest fix released at https://github.com/Infineon/linux-optiga-trust-m/commit/8bcdd37295b943476f9344cba96b3aa99bae2177
