### ISSUE TITLE
OPTIGA™ Trust M3 OpenSSL Engine usage issue

### ISSUE THREAD

**Issue by kishand-mecha** [Infineon/linux-optiga-trust-m#26]
Hi,

I am trying to Random number generation Example using below command.

`openssl rand -engine trustm_engine -base64 1024`
and facing the below error.
`Invalid engine "trustm_engine"

201006A6FFFF0000:error:13000091:engine routines:dynamic_load:version incompatibility:../openssl-3.0.5/crypto/engine/eng_dyn.c:481:
201006A6FFFF0000:error:13000074:engine routines:ENGINE_by_id:no such engine:../openssl-3.0.5/crypto/engine/eng_list.c:430:id=trustm_engine
201006A6FFFF0000:error:12800067:DSO support routines:dlfcn_load:could not load the shared library:../openssl-3.0.5/crypto/dso/dso_dlfcn.c:118:filename(libtrustm_engine.so): libtrustm_engine.so: cannot open shared object file: No such file or directory
201006A6FFFF0000:error:12800067:DSO support routines:DSO_load:could not load the shared library:../openssl-3.0.5/crypto/dso/dso_lib.c:152:
201006A6FFFF0000:error:13000084:engine routines:dynamic_load:dso not found:../openssl-3.0.5/crypto/engine/eng_dyn.c:442:
`
Could you please suggest what is the  issue?

openssl version : OpenSSL 3.0.5 5 Jul 2022 (Library: OpenSSL 3.0.5 5 Jul 2022)

**Comment by ying-css** [comment]
@kishand-mecha  Hi, Currently,  trustm_engine only supports OpenSSL 1.1.1, and work is underway to provide support for OpenSSL 3.0. We will notify you once the release for OpenSSL 3.0 is available on our public GitHub.

**Comment by ying-css** [comment]
@kishand-mecha Could you kindly advise the platform you are using? Are you also using RPI? Thanks a lot.

**Comment by kishand-mecha** [comment]
@ying-css 
Thnaks for the quick reply.
I am using imx8mm.

**Comment by ying-css** [comment]
Hi @kishand-mecha We just released Trust M provider for Openssl 3.x support. Please check out from provider_dev and test on your platform. Thanks.
