### ISSUE TITLE
Support for OpenSSL 3.0

### ISSUE THREAD

**Issue by hoinmic** [Infineon/linux-optiga-trust-m#27]
Currently I don't see any possibility to use the trustm library with the OPTIGA Trust M Security Chip in our company, because no provider for openssl 3.x is provided (according to https://github.com/Infineon/linux-optiga-trust-m#optiga-trust-m3-openssl-engine-usage only an engine for openssl 1.1.1x is provided).
Is a "provider" for openssl 3.x planned or did I misunderstand something?

**Comment by ying-css** [comment]
@hoinmic  The support for openssl 3.x is currently in progress. We will release it very soon. Thanks.

**Comment by ying-css** [comment]
Hi @hoinmic We just released Trust M provider for OpenSSL 3.x support. Please checkout from provider_dev to evaluate. Thanks.
