### ISSUE TITLE
Questions about certificates and ECC

### ISSUE THREAD

**Issue by jin-tech1** [Infineon/linux-optiga-trust-m#41]
Hello, 
Please help with the following questions.

[Q1]
How to pass a certificate, saved in fx. 0xe0e1, into the OpenSSL command "ca" using the trustm_engine? We also pass the key in, if this changes anything.

We like to avoid written the certificate to a file.

[Q2]
When trying to write a new ECC key using the "Linux Tools for Integrity and Confidentiality Protected Update", what is the "priv_key" and how to generate one that fits our chip?

Thanks for the help

**Comment by ying-css** [comment]
Hi @jin-tech1,
   For Q1, Do you mean you want to use ECC private key stored inside 0xe0f1 as CA key and ECC certificate stored inside 0xe0e1 as CA for OpenSSL function? and you don't want to readout the cert from Trust M and save it as file to use?
  For Q2, "priv_key" is the private key for Trust Anchor which provides the integrity protection. You can use the simple OpenSSL command to generate. For example, `openssl ecparam -out ecc256_privkey.pem -name prime256v1 -genkey`

**Comment by jin-tech1** [comment]
We write a Certificate into 0xe0e1 using the trustm_cert -w 0xe0e1 -i [OUR CERT]. We would like to use this OID (0xe0e1) in the OpenSSL "ca" command, something like:
`OpenSSL ca -keyform engine -engine trustm_engine -keyfile 0xe0fc:^ -cert 0xe0e1:* -config ca.conf -out cert.pem.crt -infiles test_csr.csr`

**Comment by ying-css** [comment]
Hi @jin-tech1, 
    I see. Please give us some time to check and test it out. we will come back to you very soon. Thanks.

**Comment by jin-tech1** [comment]
Hi, 

Is there any updates on this issue?
Thanks.

**Comment by ying-css** [comment]
@jin-tech1 To support this function, we need to modify the code. We need more time to implement this. Thanks.
