### ISSUE TITLE
Build failed on ARM64

### ISSUE THREAD

**Issue by Pernat1y** [Infineon/linux-optiga-trust-m#45]
**Prerequisites**

**Description**:
Unable to build latest (tree/5a762612a561a9d7eb2c948fb7b01fb7156beb5b) version of linux-optiga-trust-m.git under arm64

**Steps to Reproduce:**

1. `git clone --recurse-submodules https://github.com/Infineon/linux-optiga-trust-m.git`

2. `cd linux-optiga-trust-m`

3. `./trustm_installation_script.sh`

**Expected Result:**

Compile binaries without errors

**Actual Result:**

Build failed
Full log - https://pastebin.com/raw/pVdfyBx8

**Frequency (1/1, 1/50, 1/100):**
1/1

**Build/Commit:**

https://github.com/Infineon/linux-optiga-trust-m/tree/5a762612a561a9d7eb2c948fb7b01fb7156beb5b

**Target:**
```
ARM64
```

**Host OS and Version:**
```
Raspberry Pi OS ARM64 (Debian 12.4)
```

**Compiler:**
```
gcc (Debian 12.2.0-14) 12.2.0
```

**Environment**
```
Raspberry Pi 4 B (4GB model)
Raspberry Pi OS (Debian 12.4)
Linux rpi4.lan 6.1.0-rpi8-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.73-1+rpt1 (2024-01-25) aarch64 GNU/Linux
```

**Comment by RaymWong** [comment]
> **Prerequisites**
> 
> **Description**: Unable to build latest (tree/5a762612a561a9d7eb2c948fb7b01fb7156beb5b) version of linux-optiga-trust-m.git under arm64
> 
> **Steps to Reproduce:**
> 
> 1. `git clone --recurse-submodules https://github.com/Infineon/linux-optiga-trust-m.git`
> 2. `cd linux-optiga-trust-m`
> 3. `./trustm_installation_script.sh`
> 
> **Expected Result:**
> 
> Compile binaries without errors
> 
> **Actual Result:**
> 
> Build failed Full log - https://pastebin.com/raw/pVdfyBx8
> 
> **Frequency (1/1, 1/50, 1/100):** 1/1
> 
> **Build/Commit:**
> 
> https://github.com/Infineon/linux-optiga-trust-m/tree/5a762612a561a9d7eb2c948fb7b01fb7156beb5b
> 
> **Target:**
> 
> ```
> ARM64
> ```
> 
> **Host OS and Version:**
> 
> ```
> Raspberry Pi OS ARM64 (Debian 12.4)
> ```
> 
> **Compiler:**
> 
> ```
> gcc (Debian 12.2.0-14) 12.2.0
> ```
> 
> **Environment**
> 
> ```
> Raspberry Pi 4 B (4GB model)
> Raspberry Pi OS (Debian 12.4)
> Linux rpi4.lan 6.1.0-rpi8-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.73-1+rpt1 (2024-01-25) aarch64 GNU/Linux
> ```
> 
> ###### THANKS!

 should be fixed now thanks. #46
