### ISSUE TITLE
ECC using fixed SHA256 for signing

### ISSUE THREAD

**Issue by RaymWong** [Infineon/linux-optiga-trust-m#53]
**Prerequisites**

Can you reproduce the problem reliably? yes

Did you check current release notes for known issues? yes

If this is not the latest release, have you checked newer releases?  yes

**Description**:
The higher ECC 384/P521/B512 operation using fixed SHA 256.

https://github.com/Infineon/linux-optiga-trust-m/blob/71c04fec8e3f858186c374da9e1af07586b882e9/ex_cli_applications/trustm_ecc_sign.c#L220

**Steps to Reproduce:**

1. 

2.

3.

**Expected Result:**

**Actual Result:**

1.

2.

3.

**Expected Result:**

**Actual Result:**

**Frequency (1/1, 1/50, 1/100):**

**Build/Comm
**Frequency (1/1, 1/50, 1/100):**

**Build/Commit:**

Please specify the release, like 1.4.1. If there is no release, give us the commit for the code you used.

**Target:**

The chip or kit you are working with

**Host OS and Version:**

MacOS, Windows, Linux

**Compiler:**

Include the version!

**Environment**

Provide the context surrounding this problem. Perhaps an IDE, a debug probe, an RTOS, etc. (and versions)

**Comment by ying-css** [comment]
Fixed with the latest commits.
