### ISSUE TITLE
The X509_sign() OpenSSL API fails with EC (and works by chance with RSA)

### ISSUE THREAD

**Issue by reds71** [Infineon/linux-optiga-trust-m#63]
This OpenSSL API is especially used to sign X509 certificates and CSR (which we do). Note that OpenSSL CLI that you use for your examples and tests does not seem to use this API but an advanced one that does not reveal the issue. Anyway, the problem is the following (I debugged OpenSSL and modified the _trustm_provider_ to reach this conclusion):

By default, the signing implementation tries with the default provider (the openssl one) but with the _pkey_ created by the  _trustm_provider_. It then asks the _trustm_ "keymgmt" to export the key and tries to import it in the default OpenSSL "keymgmt". The difference between the RSA & EC behavior is that the RSA OpenSSL provider detects that the key is incomplete (see later) and raise an error that make the signing function to try with the _pkey trustm_ provider, which is not the case for the EC.

For me, like does the default OpenSSL _keymgmt_, you should block certain required exports, especially because as you handle a secure element, obviously you won't be exporting the private key. Here's what I did to make it work in `trustm_keymgmt_ec.c` (the same is applicable to RSA): 

```
int trustm_ec_keymgmt_export(void *keydata, int selection, OSSL_CALLBACK *param_
     void *pubbuff = NULL;
     size_t pubsize;
 
    if (trustm_ec_key == NULL || (selection & OSSL_KEYMGMT_SELECT_PRIVATE_KEY))
         return 0;
```
Note that hardware & sofware configuration is identical to #62

Other remarks:

- in `trustm_provider.c`, do not know if the missing query is voluntary:

```
 // todo: add ec key management here too
 static const OSSL_ALGORITHM trustm_keymgmts[] = {
-    { "RSA:rsaEncryption", NULL, trustm_rsa_keymgmt_functions },
-    { "EC:id-ecPublicKey", NULL, trustm_ec_keymgmt_functions },
+    { "RSA:rsaEncryption", "provider=trustm", trustm_rsa_keymgmt_functions },
+    { "EC:id-ecPublicKey", "provider=trustm", trustm_ec_keymgmt_functions },
     { NULL, NULL, NULL }
 };
```

- `trustm_provider_store_object.c`, some exit path on error (returns) miss structure liberation in `trustm_object_load_pkey_ec()` & `trustm_object_load_pkey_rsa()`.

Cheers.

**Comment by ying-css** [comment]
Hi @reds71 Thanks for sharing your findings. We also found the root cause and trying to fix it now. We will update the code very soon.
