### ISSUE TITLE
Input file not recognized when using pkeyutl with encrypt/decrypt functions

### ISSUE THREAD

**Issue by Oxmose** [Infineon/linux-optiga-trust-m#64]
**Description:**

When using the encrypt/decrypt pkeyutl tool with trustm provider, the operation fails due to incorrect input file.

**Steps to Reproduce:**

To decrypt, we use the following command:
`openssl pkeyutl -provider trustm_provider -inkey 0xe0fd:* -decrypt -in to_enc_long.txt -out encrypted.enc`

The output of the decrypt command is the following:
```
Input OID E0FD
Enc scheme : 11
Private OID : e0fd
inlen : 0
in is NULLError decrypting message with RSA.
Error code : 0403
Public Key operation error
```

It shows that the input file is NULL and its size is 0, while the file exists and is accessible (corret read/write rights).

To encrypt, we use the following command:
`openssl pkeyutl -provider trustm_provider -inkey 0xe0fd:^ -encrypt -in to_enc_long.txt -out encrypted.enc`

The output of the encryptcommand is the following:
```
Input OID E0FD
Enc scheme : 11
Private OID : e0fd
inlen : 0
Public Key operation error
Error encrypting message with RSA
```

It shows that the input file size is 0, while the file exists, is not empty and is accessible (corret read/write rights).

**Frequency (1/1, 1/50, 1/100):**
1/1

**Build/Commit:**

Branch: provider_dev, 934c79c703ebe092c98047315ad7a5a3980742ce

**Target:**

```
Read Chip Info [0xE0C2]: Success.
========================================================
CIM Identifier             [bCimIdentifer]: 0xcd
Platform Identifer   [bPlatformIdentifier]: 0x16
Model Identifer         [bModelIdentifier]: 0x33
ID of ROM mask                  [wROMCode]: 0x9301
Chip Type                    [rgbChipType]: 0x00 0x1c 0x00 0x05 0x00 0x00
Batch Number              [rgbBatchNumber]: 0x0a 0x02 0x61 0xd4 0x00 0x01
X-coordinate              [wChipPositionX]: 0x008e
Y-coordinate              [wChipPositionY]: 0x0033
Firmware Identifier [dwFirmwareIdentifier]: 0x80101071
Build Number                 [rgbESWBuild]: 24 40

Chip software build:
OPTIGA(TM) Trust M rev.3; Firmware Version: 3.00.2440
========================================================
```

**Host OS and Version:**

Linux 5.15.32 #1 SMP PREEMPT Tue Sep 24 12:12:55 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

**Compiler:**

gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-17)

**Environment**

OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

**Comment by ying-css** [comment]
Hi @Oxmose These two commands are not supported yet and the implementation is still in progress. We will update you once it is completed. In the meantime, we would like to share the script [RSA_openssl_enc_Trust_M_dec.sh](https://github.com/Infineon/linux-optiga-trust-m/blob/provider_dev/scripts/misc/RSA_openssl_enc_Trust_M_dec.sh) with you. This script includes the OpenSSL pkeyutl command for RSA encryption and using Trust M for decryption function. Thank you very much.

**Comment by ying-css** [comment]
Hi @Oxmose  This issue has been resolved by [the latest commit](https://github.com/Infineon/linux-optiga-trust-m/commit/93cb6c57ab382c712c60e083355f68696eda34b4.). Please refer to the test script: [RSA Encryption/Decryption using Trust M provider](https://github.com/Infineon/linux-optiga-trust-m/blob/provider_dev/provider-scripts/rsa_keygen_and_decrypt/RSA_openssl_enc_Trust_M_dec.sh) for testing. Thanks a lot.

**Comment by Oxmose** [comment]
Hi @ying-css ,

I update our lib and try the script, however, we get the following message when trying to encrypt:
```
# openssl pkeyutl -provider trustm_provider -inkey 0xe0fd:^ -encrypt -in to_enc.txt -out data.enc
Input OID E0FD
Public Key operation error
Error encrypting message with RSA
```

The key is generated as follows:
```
# openssl pkey -provider trustm_provider -in 0xe0fd:*:NEW:0x42:0x13 -pubout -out pubkey.pem
Input OID E0FD
Generating RSA keypair using TrustM....
Writing public key to OID 0xF1E1
```

**Comment by ying-css** [comment]
Hi, @Oxmose I just cloned the repo and tested it again. These two commands are working properly at my side. Could you kindly run this command under linux-optiga-trust-m directory:`./bin/trustm_metadata -r 0xf1e1 ` and send me the output of this command? Please also refer to the picture I attached here.
<img width="791" alt="RSA_Encrypt" src="https://github.com/user-attachments/assets/d94abaf8-2fa6-47be-ab87-ed8afda35965">
 Thanks.

**Comment by Oxmose** [comment]
Hi @ying-css , 

Here is the output of the command:

```
# trustm_metadata -r 0xf1e1 

========================================================
App DataStrucObj type 2     [0xF1E1]
OPTIGA execution time: 0.1484 sec.
[Size 0021] :
        20 13 C0 01 01 C4 02 05 DC C5 02 01 26 D0 03 E1
        FC 07 D1 01 00
        LcsO:0x01, Max Size:1500, Used Size:294, Change:LcsO<0x07, Read:ALW,

========================================================
```

**Comment by ying-css** [comment]
Hi @Oxmose It seems no issue with the metadata setting for 0xF1E1. Could you kindly check whether [this line](https://github.com/Infineon/linux-optiga-trust-m/blob/provider_dev/trustm_provider/trustm_provider_asym_rsa.c#L64C1-L64C52) has been added into your code? If it is not there,  Could you kindly add this line in? Also please check [this line](https://github.com/Infineon/optiga-trust-m/blob/91d952b4a6433bdbe1979487b73972b708d89b3f/optiga/include/optiga/optiga_lib_config_m_v3.h#L113) whether it has been set to "1"(Which means Soft Reset).Please refer to the picture attached here.
<img width="258" alt="SoftReset" src="https://github.com/user-attachments/assets/de4fc172-735d-4019-9d82-e200d5f1c544">
 If both can not work, Could you kindly clone the repo again into one new location, install and run the command again? Thanks

**Comment by Oxmose** [comment]
I re-cloned the repo from scratch, enabled soft reset and updated my i2c-dev. I made sure the lines you pointed out where here.

I still get the following error:
```
# openssl pkey -provider trustm_provider -in 0xe0fd:*:NEW:0x42:0x13 -pubout -out pubkey.pem
Input OID E0FD
Generating RSA keypair using TrustM....
Writing public key to OID 0xF1E1

# echo "This is to encrypt" > to_enc.txt

# openssl pkeyutl -provider trustm_provider -inkey 0xe0fd:^ -encrypt -in to_enc.txt -out data.enc
Input OID E0FD
Error in trustm_provider/trustm_provider_asym_rsa.c:102 rsa_asymcipher_encrypt: Error in optiga_crypt_rsa_encrypt_message
Public Key operation error
```

**Comment by Oxmose** [comment]
Hi @RaymWong 

Here is the output:
```
# openssl pkeyutl -provider trustm_provider -inkey 0xe0fd:^ -encrypt -in to_enc.txt -out data.enc
Input OID E0FD
[util]  optiga_util_open_application
[cmd]   optiga_cmd_open_application
[cmd]   Sending open app command...
[comms] >>>> (Data frame)
        Length of data - 0x001B
        03 00 16 08 20 F0 00 00 10 D2 76 00 00 04 47 65 
        6E 41 75 74 68 41 70 70 6C BE 40 
[comms] <<<<
        Length of data - 0x000B
        00 00 06 08 20 00 00 00 00 19 04 
[comms] >>>> (Control frame)
[cmd]   Processing response for open app command...
[cmd]   Response of open app command is processed...
[util]  optiga_util_read_metadata
[cmd]   optiga_cmd_get_data_object
[cmd]   Sending read data command...
[comms] >>>> (Data frame)
        Length of data - 0x000D
        04 00 08 08 20 81 01 00 02 E0 FD 15 26 
[comms] <<<<
        Length of data - 0x001E
        05 00 19 08 20 00 00 00 13 20 11 C0 01 01 D0 03 
        E1 FC 07 D3 01 00 E0 01 42 E1 01 13 9B E8 
[comms] >>>> (Control frame)
[cmd]   Processing response for read data command...
[cmd]   Response of read data command is processed...
[util]  optiga_util_read_data
[cmd]   optiga_cmd_get_data_object
[cmd]   Sending read data command...
[comms] >>>> (Data frame)
        Length of data - 0x0011
        09 00 0C 08 20 81 00 00 06 F1 E1 00 00 06 11 AD 
        0C 
[comms] <<<<
        Length of data - 0x0115
        0A 01 10 09 20 00 00 01 26 30 82 01 22 30 0D 06 
        09 2A 86 48 86 F7 0D 01 01 01 05 00 03 82 01 0F 
        00 30 82 01 0A 02 82 01 01 00 98 C4 D6 60 5B C6 
        FD 8D 53 B9 41 9D FD AB 08 7A D5 79 3C 42 56 CA 
        C6 B7 24 9B F5 53 84 E0 A5 98 7C 95 B9 E9 55 AA 
        6C 44 61 56 6A AB 4D A4 F4 22 AA E0 9C CE 1B 36 
        FE 34 18 3B 9F A4 D1 55 E1 59 81 67 92 65 49 65 
        19 F9 D4 FA 99 50 01 D5 AF 7D D3 CD 9F 10 7B 92 
        65 B5 C7 E1 5B 82 6F 65 8B D5 11 69 B1 CF 1C D6 
        F6 8F 92 57 BD AA 5D 83 EA A6 71 D4 4A 59 96 C5 
        7E 7C 20 89 2A 4C 81 92 9E BB BD 5C 0A 95 47 45 
        DB AD 61 E7 58 75 6A 25 3C 35 6A D2 E9 5B 0D B8 
        38 D3 94 97 AA BF 18 2C 7A 58 EF 33 A3 0E 79 32 
        F8 39 2C 48 91 20 9C 8E F1 ED 39 2F 55 C6 4A 39 
        E6 57 B0 FD 58 3A 36 DE D0 A9 B3 39 8B 56 5E AC 
        4B 73 00 D8 31 A1 50 87 8B 3D 61 1D 3A 42 7B A6 
        83 9A 2F BC A3 04 F0 BB FF C4 E1 4F 6C 04 3F 05 
        7F 36 53 11 AF 
[comms] >>>> (Control frame)
[comms] <<<<
        Length of data - 0x0022
        0E 00 1D 0C D2 6C 13 62 0E 0C 30 AE B7 37 D4 26 
        84 02 E3 A7 1B B6 80 BE 4F 5F 75 02 03 01 00 01 
        CB 99 
[comms] >>>> (Control frame)
[cmd]   Processing response for read data command...
[cmd]   Response of read data command is processed...
[crypt] optiga_crypt_rsa_encrypt_message
Error in trustm_provider/trustm_provider_asym_rsa.c:102 rsa_asymcipher_encrypt: Error in optiga_crypt_rsa_encrypt_message
Public Key operation error
```
