### ISSUE TITLE
RSA key export to OpenSSL fails

### ISSUE THREAD

**Issue by reds71** [Infineon/linux-optiga-trust-m#66]
Hello,

The OpenSSL provider (`trustm_provider` branch) 'keymgmt' for RSA does not export the key exponent because of a bug located at _trustm_keymgmt_rsa.c:508_

```
@@ -505,7 +505,7 @@ int trustm_rsa_keymgmt_export(void *keydata, int selection, OSSL_CALLBACK *param
                                         trustm_rsa_key->modulus,
                                         trustm_rsa_key->modulus_length);
         exponent = 0x10001;
-        *p = OSSL_PARAM_construct_BN(OSSL_PKEY_PARAM_RSA_E, (unsigned char*)&exponent, sizeof(exponent));
+        *p++ = OSSL_PARAM_construct_BN(OSSL_PKEY_PARAM_RSA_E, (unsigned char*)&exponent, sizeof(exponent));
     }
     *p = OSSL_PARAM_construct_end();
```
Currently, the exponent param is overwritten by the call to `OSSL_PARAM_construct_end`

Best regards

**Comment by ying-css** [comment]
Hi @reds71 Thank you very much for pointing out this bug for us. We will update this part in next commit.

**Comment by reds71** [comment]
Hi @ying-css . Is there a way to exchange out-of-band with you ? I found a tricky issue...

**Comment by reds71** [comment]
Thanks. I will write you asap. Maybe you should remove you e-mail from the public forum.

**Comment by reds71** [comment]
Hi @ying-css,

I think this issue was one of the earliest closed, but I did not see the fix appearing in your commit?

**Comment by ying-css** [comment]
Hi @reds71 Yes, We didn't release the fix yet and will update this part in next commit. Thanks.
