### ISSUE TITLE
Could not make RSA decryption work

### ISSUE THREAD

**Issue by reds71** [Infineon/linux-optiga-trust-m#68]
Hi,
Trying to encrypt/decrypt data using the _OpenSSL_ API, we had to decrypt data using the `EVP_PKEY_decrypt()` API with data that was:
- encrypted by the _OpenSSL_ default provider,
- encrypted by the _Trust M_ one.

In both case the decrypt fails and we can see the following traces from the provider:

```
Enc scheme : 11
Private OID : e0fd
inlen : 256
Error decrypting message with RSA.
Error code : 0403
```
Since you do not seem to use the _OpenSSL_ API, maybe you will be able reproduce it using the `openssl rsautl` command with `-encrypt/decrypt` options ?

BR,

**Comment by ying-css** [comment]
Hi @reds71 The implementation of using Trust M provider for RSA decryption is still in progress. We will notify you once it is completed. In the meantime, we would like to share the script [RSA_openssl_enc_Trust_M_dec.sh](https://github.com/Infineon/linux-optiga-trust-m/blob/provider_dev/scripts/misc/RSA_openssl_enc_Trust_M_dec.sh) with you. This script includes the OpenSSL pkeyutl command for RSA encryption and using Trust M CLI for RSA decryption function. Thank you very much.

**Comment by ying-css** [comment]
Hi @reds71, This issue has been resolved by [the latest commit](https://github.com/Infineon/linux-optiga-trust-m/commit/93cb6c57ab382c712c60e083355f68696eda34b4). Please refer to the test script: [RSA Encryption/Decryption using Trust M provider](https://github.com/Infineon/linux-optiga-trust-m/blob/provider_dev/provider-scripts/rsa_keygen_and_decrypt/RSA_openssl_enc_Trust_M_dec.sh) for testing. Thanks a lot.
